# Generated by Django 2.2.1 on 2019-06-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TODO',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing', models.CharField(max_length=20, verbose_name='待办事项')),
                ('done', models.BooleanField(default=False, verbose_name='已完成')),
            ],
            options={
                'db_table': 'todolist',
            },
        ),
    ]
