# Generated by Django 2.2.1 on 2019-06-19 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
