# Generated by Django 2.2.1 on 2019-06-19 02:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0002_todo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='name',
        ),
    ]
