# Generated by Django 2.2.1 on 2019-06-19 06:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0003_remove_todo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('name', models.CharField(max_length=10)),
                ('apartment', models.TextField()),
                ('birthday', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
